In [1]:
import numpy as np

In [16]:
arr = np.random.randn(4)
arr

array([-1.49862294,  1.51193185, -0.4295977 ,  0.46960542])

In [18]:
sor = np.sort(arr)# Tartiblangan versiyasi
sor

array([-1.49862294, -0.4295977 ,  0.46960542,  1.51193185])

In [21]:
arr.sort()# tartiblaydi
arr

array([-1.49862294, -0.4295977 ,  0.46960542,  1.51193185])

In [27]:
reve = -np.sort(-arr)
reve

array([ 1.51193185,  0.46960542, -0.4295977 , -1.49862294])

In [31]:
arrt = np.random.randn(2,4)
arrt

array([[-0.08832333, -1.42710798,  0.29725226, -0.78677539],
       [ 0.36306749,  0.29289158,  0.34140293, -0.36840494]])

In [33]:
#axis 0 qator
rov = np.sort(arrt,axis=0)
rov

array([[-0.08832333, -1.42710798,  0.29725226, -0.78677539],
       [ 0.36306749,  0.29289158,  0.34140293, -0.36840494]])

In [35]:
#axis=1 ustun
col= np.sort(arrt,axis = 1)
col

array([[-1.42710798, -0.78677539, -0.08832333,  0.29725226],
       [-0.36840494,  0.29289158,  0.34140293,  0.36306749]])