In [1]:
import numpy as np

In [13]:
arr1 = np.arange(1,7).reshape(2,3)# 1 dan 7 gacha bo'lgan arr
arr2 = np.arange(7,13).reshape(2,3)# 7 dan 12 gacha bo'lgan arr

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [16]:
arr1*arr2# arr1 ning elementlarini arr2 ga ko'paytiradi

array([[ 7, 16, 27],
       [40, 55, 72]])

In [17]:
# bo'lish
arr2 / arr1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [19]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [20]:
arr2 - arr1

array([[6, 6, 6],
       [6, 6, 6]])

In [21]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
arr2**0.5

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])