In [1]:
import numpy as np

In [4]:
arr = np.random.randn(5,4)#(5,4) massiv\
arr

array([[ 0.07781893, -0.7919364 ,  0.35692057, -1.89191129],
       [-0.36318624, -0.81748928, -1.31631737,  0.05225999],
       [-0.32122243,  0.62743575, -0.25597583,  0.47800188],
       [-1.94701927, -1.17745783,  0.68387491, -0.61488745],
       [ 0.28424415,  1.09675337,  0.20431518,  0.18975211]])

In [5]:
arr.sum()#BARCHA ELEMENT YIG"INDI

-5.44602654969913

In [6]:
np.sum(arr)

-5.44602654969913

In [9]:
a=arr[0,:]
a.sum()

-2.2491081853250297

In [13]:
arr.sum(axis=1)# qator yig'indi

array([-2.24910819, -2.4447329 ,  0.52823937, -3.05548964,  1.77506481])

In [14]:
arr.sum(axis=0)# ustun yig'indi

array([-2.26936487, -1.06269438, -0.32718253, -1.78678476])

In [17]:
ar= np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [19]:
mean = np.sum(ar/len(ar))
mean

2.0

In [20]:
np.mean(ar)

2.0

In [21]:
ar.mean()

2.0

In [22]:
arr

array([[ 0.07781893, -0.7919364 ,  0.35692057, -1.89191129],
       [-0.36318624, -0.81748928, -1.31631737,  0.05225999],
       [-0.32122243,  0.62743575, -0.25597583,  0.47800188],
       [-1.94701927, -1.17745783,  0.68387491, -0.61488745],
       [ 0.28424415,  1.09675337,  0.20431518,  0.18975211]])

In [25]:
np.mean(arr)

-0.2723013274849565

In [27]:
np.mean(arr, axis=1)#qator bo'yicha

array([-0.56227705, -0.61118323,  0.13205984, -0.76387241,  0.4437662 ])

In [28]:
np.mean(arr, axis=0)#ustunlar bo'yicha

array([-0.45387297, -0.21253888, -0.06543651, -0.35735695])

In [29]:
 ar

array([0, 1, 2, 3, 4])

In [30]:
np.cumsum(ar)

array([ 0,  1,  3,  6, 10])