In [1]:
import numpy as np

In [8]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])

In [9]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
y=np.array([[5.,5.,5.],[4.,4.,4.]])

In [11]:
y

array([[5., 5., 5.],
       [4., 4., 4.]])

In [12]:
x+y

array([[ 6.,  7.,  8.],
       [ 8.,  9., 10.]])

In [13]:
y-x

array([[ 4.,  3.,  2.],
       [ 0., -1., -2.]])

In [14]:
x*5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [16]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
y=np.array([[6.,23.],[-1.,7.],[8.,9.]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [18]:
x.dot(y)#x*y

array([[ 28.,  64.],
       [ 67., 181.]])

In [19]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [20]:
y.dot(x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [21]:
np.dot(y,x)

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [27]:
from numpy.linalg import inv